/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SchemaRouteImport } from './routes/schema'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProcessorsRouteImport } from './routes/processors'
import { Route as FieldValueRouteImport } from './routes/$field/$value'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemaRoute = SchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessorsRoute = ProcessorsRouteImport.update({
  id: '/processors',
  path: '/processors',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldValueRoute = FieldValueRouteImport.update({
  id: '/$field/$value',
  path: '/$field/$value',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings/api-keys': typeof ApiKeysRoute
  '/dashboard': typeof DashboardRoute
  '/schema': typeof SchemaRoute
  '/reports': typeof ReportsRoute
  '/processors': typeof ProcessorsRoute
  '/$field/$value': typeof FieldValueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/api-keys': typeof ApiKeysRoute
  '/dashboard': typeof DashboardRoute
  '/schema': typeof SchemaRoute
  '/reports': typeof ReportsRoute
  '/processors': typeof ProcessorsRoute
  '/$field/$value': typeof FieldValueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings/api-keys': typeof ApiKeysRoute
  '/dashboard': typeof DashboardRoute
  '/schema': typeof SchemaRoute
  '/reports': typeof ReportsRoute
  '/processors': typeof ProcessorsRoute
  '/$field/$value': typeof FieldValueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings/api-keys' | '/dashboard' | '/schema' | '/reports' | '/processors' | '/$field/$value'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings/api-keys' | '/dashboard' | '/schema' | '/reports' | '/processors' | '/$field/$value'
  id: '__root__' | '/' | '/settings/api-keys' | '/dashboard' | '/schema' | '/reports' | '/processors' | '/$field/$value'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiKeysRoute: typeof ApiKeysRoute
  DashboardRoute: typeof DashboardRoute
  SchemaRoute: typeof SchemaRoute
  ReportsRoute: typeof ReportsRoute
  ProcessorsRoute: typeof ProcessorsRoute
  FieldValueRoute: typeof FieldValueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schema': {
      id: '/schema'
      path: '/schema'
      fullPath: '/schema'
      preLoaderRoute: typeof SchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processors': {
      id: '/processors'
      path: '/processors'
      fullPath: '/processors'
      preLoaderRoute: typeof ProcessorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$field/$value': {
      id: '/$field/$value'
      path: '/$field/$value'
      fullPath: '/$field/$value'
      preLoaderRoute: typeof FieldValueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiKeysRoute: ApiKeysRoute,
  DashboardRoute: DashboardRoute,
  SchemaRoute: SchemaRoute,
  ReportsRoute: ReportsRoute,
  ProcessorsRoute: ProcessorsRoute,
  FieldValueRoute: FieldValueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
